### ISSUE TITLE
Client Instantiation Fails - InvalidRegionError

### ISSUE THREAD

**Issue by L3XANDR0** [IBM/ibm-cos-sdk-python#42] opened 2021-05-18 16:36 UTC
I attempted to run the IBM COS Python SDK example here: https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-sdk-gs

The sample code is failing when ibm_boto3.client() is called.
```
Exception has occurred: InvalidRegionError
     Provided region_name 'US_WEST_1' doesn't match a supported format.
```

The relevant code, withouth API key and service crn. 
```
# Constants for IBM COS values
COS_ENDPOINT = "https://s3.us-south.cloud-object-storage.appdomain.cloud"
COS_API_KEY_ID = # example: xxxd12V2QHXbjaM99G9tWyYDgF_0gYdlQ8aWALIQxXx4
COS_AUTH_ENDPOINT = "https://iam.cloud.ibm.com/identity/token"
COS_SERVICE_CRN = # example: crn:v1:bluemix:public:cloud-object-storage:global:a/xx999cd94a0dda86fd8eff3191349999:9999b05b-x999-4917-xxxx-9d5b326a1111::
COS_STORAGE_CLASS = "us-south-standard"

# Create client connection
cos_cli = ibm_boto3.client("s3",
    ibm_api_key_id=COS_API_KEY_ID,
    ibm_service_instance_id=COS_SERVICE_CRN,
    ibm_auth_endpoint=COS_AUTH_ENDPOINT,
    config=Config(signature_version="oauth"),
    endpoint_url=COS_ENDPOINT
)
```

I'm using Python version: 3.8.3, with the following modules.
```
boto3==1.17.74
ibm-cloud-sdk-core==3.10.0
ibm-cos-sdk==2.10.0
ibm-cos-sdk-core==2.10.0
ibm-cos-sdk-s3transfer==2.10.0
```

**Comment by nglange** [comment] 2021-05-18 17:32
Thanks for the report - that seems to be very strange. I wonder if there's some crosstalk happening between the vanilla `boto3` library and the IBM fork. I'll poke around and see if I can figure out where the `US_WEST_1` is coming from. All the code you show looks perfectly correct.

**Comment by kundanone** [comment] 2021-07-30 06:19
I also faced the same issue, and I have a workaround:
I can see that the root cause is its validator method:
link: https://github.com/IBM/ibm-cos-sdk-python-core/blob/18e8a854a2a4fdca7fbb50d5b80fb666734def1f/ibm_botocore/utils.py#L1004

`def validate_region_name(region_name):
    """Provided region_name must be a valid host label."""
    if region_name is None:
        return
    valid_host_label = re.compile(r'^(?![0-9]+$)(?!-)[a-zA-Z0-9-]{,63}(?<!-)$')
    valid = valid_host_label.match(region_name)
    if not valid:
        raise InvalidRegionError(region_name=region_name)`
Workaround:
comment out last two lines:
`    # if not valid:
    #     raise InvalidRegionError(region_name=region_name)`
When i generate a service api key, it has  "-" in the string which fails the validation :
e.g. api key: ***********************V4kt4-OH4klr_qtoXsF
the validator need to be updated as it is not accepting new api key which has "-'' chars in it.

**Comment by L3XANDR0** [comment] 2021-08-11 20:49
@nglange Any movement on this?

**Comment by L3XANDR0** [comment] 2021-12-30 20:23
I continue to hit this issue.

**Comment by IBMeric** [comment] 2022-01-04 18:20
@nglange Could you look at this again?

**Comment by avinash1IBM** [comment] 2023-05-12 06:25
@L3XANDR0 could you please check again with. 
ibm-cos-sdk            2.13.0
ibm-cos-sdk-core       2.13.0
ibm-cos-sdk-s3transfer 2.13.0

**Comment by avinash1IBM** [comment] 2023-07-10 05:58
We are closing this issue as resolved as there is no further communication. Please create a new issue if you are facing the same problem again.

**Closed by avinash1IBM** 2023-07-10 05:58 UTC
