### ISSUE TITLE
Frequently hitting AsperaTransferFailedError : Server aborted session: Docroot check failed: 

### ISSUE THREAD

**Issue by AmarnatReddy** [IBM/ibm-cos-sdk-python#55] opened 2023-01-21 13:12 UTC
We are using cos for uploading the files to object storage.
we are hitting the below issue 

```
2023-01-21 11:25:38,308 (ibmcos.aspera) [INFO] - Queue processing thread started
2023-01-21 11:25:39,757 (ibmcos.aspera) [INFO] - ASCP process queue - Max(10) InUse(0) Free(10) New(1)
2023-01-21 11:25:39,870 (ibmcos.aspera) [INFO] - 553ab1bd5220-XXXXXXXXXXX : INIT
2023-01-21 11:25:40,440 (ibmcos.aspera) [INFO] - 553ab1bd5220-XXXXXXXXXXX : ERROR
2023-01-21 11:25:40,440 (ibmcos.aspera) [ERROR] - AsperaTransferFailedError : Server aborted session: Docroot check failed: Failed to authenticate: : Error getting token from delegated refresh token: aspera.clouds.ibm.icos.oauth.IbmOAuthException: Wrong client id passed to retrieve tokens for a delegated refresh token. (The delegat
2023-01-21 11:25:40,440 (ibmcos.aspera) [INFO] - Remove from processing queue count=1
2023-01-21 11:25:40,440 (ibmcos.aspera) [INFO] - Freeing resources: 094e8b32-f45a-451b-9255-XXXXXXXXXX
2023-01-21 11:25:41,567 (ibmcos.aspera) [INFO] - Queue processing thread stopped
2023-01-21 11:25:41,568 (__main__) [ERROR] - Server aborted session: Docroot check failed: Failed to authenticate: : Error getting token from delegated refresh token: aspera.clouds.ibm.icos.oauth.IbmOAuthException: Wrong client id passed to retrieve tokens for a delegated refresh token. (The delegat
```
Same when we re-run it is passing.

Can you please suggest why this is happening

**Comment by IBMalok** [comment] 2023-01-24 07:34
@AmarnatReddy - 
Support for Aspera in the COS SDKs is currently “legacy”: https://github.com/IBM/ibm-cos-sdk-python#legacy-aspera-high-speed-transfer. Please use [aspera-transfer-sdk](https://developer.ibm.com/apis/catalog/aspera--aspera-transfer-sdk/Introduction/) instead.

**Comment by IBMalok** [comment] 2023-02-14 07:06
@AmarnatReddy - Can you please close the ticket if the issue is resolved?
Thanks.

**Comment by avinash1IBM** [comment] 2023-04-07 07:41
Closing this issue  as resolved

**Closed by avinash1IBM** 2023-04-07 07:41 UTC
